// Array di immagini (inserisci qui i percorsi delle tue immagini di farmaci)
const images = [
    'images/fenossimetilpenicillina.png',
    'images/benzilpenicillina.png',
    'images/meticillina.png' ,
'images/nafcillina.png' ,
'images/oxacillina.png' ,
'images/cloxacillina.png' ,
'images/dicloxacillina.png' ,
'images/flucloxacillina.png' ,
'images/ampicillina.png' ,
'images/amoxicillina.png' ,
'images/pivampicillina.png' ,
'images/mezlocillina.png' ,
'images/piperacillina.png' ,
'images/azlocillina.png' ,
'images/carbenicillina.png' ,
'images/ticarcillina.png' ,
'images/sulbenicillina.png' ,
'images/probenecid.png' ,
'images/acidoclavulanico.png' ,
'images/sulbactam.png' ,
'images/tazobactam.png' ,
'images/cefalexina.png' ,
'images/cefalotina.png' ,
'images/cefaloridina.png' ,
'images/cefadroxile.png' ,
'images/cefuroxima_axetil.png' ,
'images/cefoxitina.png' ,
'images/cefuroxima.png' ,
'images/cefaclor.png' ,
'images/cefotaxima.png' ,
'images/ceftizoxima.png' ,
'images/ceftriaxone.png' ,
'images/ceftazidima.png' ,
'images/cefepima.png' ,
'images/tienamicina.png' ,
'images/imipenem.png' ,
'images/ertapenem.png' ,
'images/meropenem.png' ,
'images/aztreonam.png' ,
'images/cicloserina.png' ,
'images/fosfomicina.png' ,
'images/eritromicina.png' ,
'images/claritromicina.png' ,
'images/azitromicina.png' ,
'images/tetraciclina.png' ,
'images/demeclociclina.png' ,
'images/clortetraciclina.png' ,
'images/minociclina.png' ,
'images/doxiciclina.png' ,
'images/metaciclina.png' ,
'images/ossitetraciclina.png' ,
'images/tigeciclina.png' ,
'images/streptomicina.png' ,
'images/kanamicina.png' ,
'images/gentamicina.png' ,
'images/neomicina.png' ,
'images/amicacina.png' ,
'images/netilmicina.png' ,
'images/tobramicina.png' ,
'images/rifampicina.png' ,
'images/cloramfenicolo.png' ,
'images/tiamfenicolo.png' ,
'images/sulfafurazolo.png' ,
'images/sulfatiazolo.png' ,
'images/sulfadimetossina.png' ,
'images/sulfametossipiridina.png' ,
'images/sulfaguanidina.png' ,
'images/sulfacetamide.png' ,
'images/sulfadiazina.png' ,
'images/sulfalene.png' ,
'images/sulfadossina.png' ,
'images/sulfametossazolo.png' ,
'images/sulfisossazolo.png' ,
'images/acido_nalidixico.png' ,
'images/cinoxacina.png' ,
'images/acido_oxolinico.png' ,
'images/acido_pipemidico.png' ,
'images/norfloxacina.png' ,
'images/ofloxacina.png' ,
'images/grepafloxacina.png' ,
'images/sparfloxacina.png' ,
'images/gemifloxacina.png' ,
'images/moxifloxacina.png' ,
'images/trimetoprim.png' ,
];

// Funzione per mostrare un'immagine casuale
function showRandomImage() {
    const randomIndex = Math.floor(Math.random() * images.length);
    document.getElementById('drugImage').src = images[randomIndex];
}
